
exports.up = function (knex, Promise) {
  return knex('countries').insert([
    { name: 'International', formalName: '' },
    { name: 'Abkhazia', formalName: 'Republic of Abkhazia' },
    { name: 'Afghanistan', formalName: 'Islamic Republic of Afghanistan' },
    { name: 'Albania', formalName: 'Republic of Albania' },
    { name: 'Algeria', formalName: "People's Democratic Republic of Algeria" },
    { name: 'Andorra', formalName: 'Principality of Andorra' },
    { name: 'Angola', formalName: 'Republic of Angola' },
    { name: 'Antigua and Barbuda', formalName: '' },
    { name: 'Argentina', formalName: 'Argentine Republic' },
    { name: 'Armenia', formalName: 'Republic of Armenia' },
    { name: 'Australia', formalName: 'Commonwealth of Australia' },
    { name: 'Austria', formalName: 'Republic of Austria' },
    { name: 'Azerbaijan', formalName: 'Republic of Azerbaijan' },
    { name: 'Bahamas, The', formalName: 'Commonwealth of the Bahamas' },
    { name: 'Bahrain', formalName: 'Kingdom of Bahrain' },
    { name: 'Bangladesh', formalName: "People's Republic of Bangladesh" },
    { name: 'Barbados', formalName: '' },
    { name: 'Belarus', formalName: 'Republic of Belarus' },
    { name: 'Belgium', formalName: 'Kingdom of Belgium' },
    { name: 'Belize', formalName: '' },
    { name: 'Benin', formalName: 'Republic of Benin' },
    { name: 'Bhutan', formalName: 'Kingdom of Bhutan' },
    { name: 'Bolivia', formalName: 'Plurinational State of Bolivia' },
    { name: 'Bosnia and Herzegovina', formalName: '' },
    { name: 'Botswana', formalName: 'Republic of Botswana' },
    { name: 'Brazil', formalName: 'Federative Republic of Brazil' },
    { name: 'Brunei', formalName: 'Nation of Brunei, Abode of Peace' },
    { name: 'Bulgaria', formalName: 'Republic of Bulgaria' },
    { name: 'Burkina Faso', formalName: '' },
    { name: 'Burundi', formalName: 'Republic of Burundi' },
    { name: 'Cambodia', formalName: 'Kingdom of Cambodia' },
    { name: 'Cameroon', formalName: 'Republic of Cameroon' },
    { name: 'Canada', formalName: '' },
    { name: 'Cape Verde', formalName: 'Republic of Cabo Verde' },
    { name: 'Central African Republic', formalName: '' },
    { name: 'Chad', formalName: 'Republic of Chad' },
    { name: 'Chile', formalName: 'Republic of Chile' },
    { name: 'China', formalName: "People's Republic of China" },
    { name: 'Colombia', formalName: 'Republic of Colombia' },
    { name: 'Comoros', formalName: 'Union of the Comoros' },
    { name: 'Congo, Democratic Republic of the', formalName: '' },
    { name: 'Congo, Republic of the', formalName: '' },
    { name: 'Cook Islands', formalName: '' },
    { name: 'Costa Rica', formalName: 'Republic of Costa Rica' },
    { name: 'Croatia', formalName: 'Republic of Croatia' },
    { name: 'Cuba', formalName: 'Republic of Cuba' },
    { name: 'Cyprus', formalName: 'Republic of Cyprus' },
    { name: 'Czech Republic', formalName: '' },
    { name: 'Denmark', formalName: 'Kingdom of Denmark' },
    { name: 'Djibouti', formalName: 'Republic of Djibouti' },
    { name: 'Dominica', formalName: 'Commonwealth of Dominica' },
    { name: 'Dominican Republic', formalName: '' },
    { name: 'East Timor', formalName: 'Democratic Republic of Timor-Leste' },
    { name: 'Ecuador', formalName: 'Republic of Ecuador' },
    { name: 'Egypt', formalName: 'Arab Republic of Egypt' },
    { name: 'El Salvador', formalName: 'Republic of El Salvador' },
    { name: 'Equatorial Guinea', formalName: 'Republic of Equatorial Guinea' },
    { name: 'Eritrea', formalName: 'State of Eritrea' },
    { name: 'Estonia', formalName: 'Republic of Estonia' },
    { name: 'Ethiopia', formalName: 'Federal Democratic Republic of Ethiopia' },
    { name: 'Federated States of Micronesia', formalName: '' },
    { name: 'Fiji', formalName: 'Republic of Fiji' },
    { name: 'Finland', formalName: 'Republic of Finland' },
    { name: 'France', formalName: 'French Republic' },
    { name: 'Gabon', formalName: 'Gabonese Republic' },
    { name: 'Gambia, The', formalName: 'Republic of the Gambia' },
    { name: 'Georgia', formalName: '' },
    { name: 'Germany', formalName: 'Federal Republic of Germany' },
    { name: 'Ghana', formalName: 'Republic of Ghana' },
    { name: 'Greece', formalName: 'Hellenic Republic' },
    { name: 'Grenada', formalName: '' },
    { name: 'Guatemala', formalName: 'Republic of Guatemala' },
    { name: 'Guinea', formalName: 'Republic of Guinea' },
    { name: 'Guinea-Bissau', formalName: 'Republic of Guinea-Bissau' },
    { name: 'Guyana', formalName: 'Co-operative Republic of Guyana' },
    { name: 'Haiti', formalName: 'Republic of Haiti' },
    { name: 'Honduras', formalName: 'Republic of Honduras' },
    { name: 'Hungary', formalName: '' },
    { name: 'Iceland', formalName: '' },
    { name: 'India', formalName: 'Republic of India' },
    { name: 'Indonesia', formalName: 'Republic of Indonesia' },
    { name: 'Iran', formalName: 'Islamic Republic of Iran' },
    { name: 'Iraq', formalName: 'Republic of Iraq' },
    { name: 'Ireland', formalName: '' },
    { name: 'Israel', formalName: 'State of Israel' },
    { name: 'Italy', formalName: 'Italian Republic' },
    { name: 'Ivory Coast', formalName: "Republic of Côte d'Ivoire" },
    { name: 'Jamaica', formalName: '' },
    { name: 'Japan', formalName: '' },
    { name: 'Jordan', formalName: 'Hashemite Kingdom of Jordan' },
    { name: 'Kazakhstan', formalName: 'Republic of Kazakhstan' },
    { name: 'Kenya', formalName: 'Republic of Kenya' },
    { name: 'Kiribati', formalName: 'Republic of Kiribati' },
    { name: 'Korea, North', formalName: "Democratic People's Republic of Korea" },
    { name: 'Korea, South', formalName: 'Republic of Korea' },
    { name: 'Kosovo', formalName: 'Republic of Kosovo' },
    { name: 'Kuwait', formalName: 'State of Kuwait' },
    { name: 'Kyrgyzstan', formalName: 'Kyrgyz Republic' },
    { name: 'Laos', formalName: "Lao People's Democratic Republic" },
    { name: 'Latvia', formalName: 'Republic of Latvia' },
    { name: 'Lebanon', formalName: 'Lebanese Republic' },
    { name: 'Lesotho', formalName: 'Kingdom of Lesotho' },
    { name: 'Liberia', formalName: 'Republic of Liberia' },
    { name: 'Libya', formalName: 'State of Libya' },
    { name: 'Liechtenstein', formalName: 'Principality of Liechtenstein' },
    { name: 'Lithuania', formalName: 'Republic of Lithuania' },
    { name: 'Luxembourg', formalName: 'Grand Duchy of Luxembourg' },
    { name: 'Macedonia', formalName: 'Republic of Macedonia' },
    { name: 'Madagascar', formalName: 'Republic of Madagascar' },
    { name: 'Malawi', formalName: 'Republic of Malawi' },
    { name: 'Malaysia', formalName: '' },
    { name: 'Maldives', formalName: 'Republic of Maldives' },
    { name: 'Mali', formalName: 'Republic of Mali' },
    { name: 'Malta', formalName: 'Republic of Malta' },
    { name: 'Marshall Islands', formalName: 'Republic of the Marshall Islands' },
    { name: 'Mauritania', formalName: 'Islamic Republic of Mauritania' },
    { name: 'Mauritius', formalName: 'Republic of Mauritius' },
    { name: 'Mexico', formalName: 'United Mexican States' },
    { name: 'Moldova', formalName: 'Republic of Moldova' },
    { name: 'Monaco', formalName: 'Principality of Monaco' },
    { name: 'Mongolia', formalName: '' },
    { name: 'Montenegro', formalName: '' },
    { name: 'Morocco', formalName: 'Kingdom of Morocco' },
    { name: 'Mozambique', formalName: 'Republic of Mozambique' },
    { name: 'Myanmar', formalName: 'Republic of the Union of Myanmar' },
    { name: 'Nagorno-Karabakh', formalName: 'Nagorno-Karabakh Republic' },
    { name: 'Namibia', formalName: 'Republic of Namibia' },
    { name: 'Nauru', formalName: 'Republic of Nauru' },
    { name: 'Nepal', formalName: 'Federal Democratic Republic of Nepal' },
    { name: 'Netherlands', formalName: 'Kingdom of the Netherlands' },
    { name: 'New Zealand', formalName: '' },
    { name: 'Nicaragua', formalName: 'Republic of Nicaragua' },
    { name: 'Niger', formalName: 'Republic of Niger' },
    { name: 'Nigeria', formalName: 'Federal Republic of Nigeria' },
    { name: 'Niue', formalName: '' },
    { name: 'Northern Cyprus', formalName: 'Turkish Republic of Northern Cyprus' },
    { name: 'Norway', formalName: 'Kingdom of Norway' },
    { name: 'Oman', formalName: 'Sultanate of Oman' },
    { name: 'Pakistan', formalName: 'Islamic Republic of Pakistan' },
    { name: 'Palau', formalName: 'Republic of Palau' },
    { name: 'Palestine', formalName: 'State of Palestine' },
    { name: 'Panama', formalName: 'Republic of Panama' },
    { name: 'Papua New Guinea', formalName: 'Independent State of Papua New Guinea' },
    { name: 'Paraguay', formalName: 'Republic of Paraguay' },
    { name: 'Peru', formalName: 'Republic of Peru' },
    { name: 'Philippines', formalName: 'Republic of the Philippines' },
    { name: 'Poland', formalName: 'Republic of Poland' },
    { name: 'Portugal', formalName: 'Portuguese Republic' },
    { name: 'Qatar', formalName: 'State of Qatar' },
    { name: 'Romania', formalName: '' },
    { name: 'Russia', formalName: 'Russian Federation' },
    { name: 'Rwanda', formalName: 'Republic of Rwanda' },
    { name: 'Sahrawi Arab Democratic Republic', formalName: '' },
    { name: 'Saint Kitts and Nevis', formalName: 'Federation of Saint Christopher and Nevis' },
    { name: 'Saint Lucia', formalName: '' },
    { name: 'Saint Vincent and the Grenadines', formalName: '' },
    { name: 'Samoa', formalName: 'Independent State of Samoa' },
    { name: 'San Marino', formalName: 'Republic of San Marino' },
    { name: 'São Tomé and Príncipe', formalName: 'Democratic Republic of São Tomé and Príncipe' },
    { name: 'Saudi Arabia', formalName: 'Kingdom of Saudi Arabia' },
    { name: 'Senegal', formalName: 'Republic of Senegal' },
    { name: 'Serbia', formalName: 'Republic of Serbia' },
    { name: 'Seychelles', formalName: 'Republic of Seychelles' },
    { name: 'Sierra Leone', formalName: 'Republic of Sierra Leone' },
    { name: 'Singapore', formalName: 'Republic of Singapore' },
    { name: 'Slovakia', formalName: 'Slovak Republic' },
    { name: 'Slovenia', formalName: 'Republic of Slovenia' },
    { name: 'Solomon Islands', formalName: '' },
    { name: 'Somalia', formalName: 'Federal Republic of Somalia' },
    { name: 'Somaliland', formalName: 'Republic of Somaliland' },
    { name: 'South Africa', formalName: 'Republic of South Africa' },
    { name: 'South Ossetia', formalName: 'Republic of South Ossetia' },
    { name: 'South Sudan', formalName: 'Republic of South Sudan' },
    { name: 'Spain', formalName: 'Kingdom of Spain' },
    { name: 'Sri Lanka', formalName: 'Democratic Socialist Republic of Sri Lanka' },
    { name: 'Sudan', formalName: 'Republic of the Sudan' },
    { name: 'Suriname', formalName: 'Republic of Suriname' },
    { name: 'Swaziland', formalName: 'Kingdom of Swaziland' },
    { name: 'Sweden', formalName: 'Kingdom of Sweden' },
    { name: 'Switzerland', formalName: 'Swiss Confederation' },
    { name: 'Syria', formalName: 'Syrian Arab Republic' },
    { name: 'Taiwan', formalName: 'Republic of China' },
    { name: 'Tajikistan', formalName: 'Republic of Tajikistan' },
    { name: 'Tanzania', formalName: 'United Republic of Tanzania' },
    { name: 'Thailand', formalName: 'Kingdom of Thailand' },
    { name: 'Togo', formalName: 'Togolese Republic' },
    { name: 'Tonga', formalName: 'Kingdom of Tonga' },
    { name: 'Transnistria', formalName: 'Pridnestrovian Moldavian Republic' },
    { name: 'Trinidad and Tobago', formalName: 'Republic of Trinidad and Tobago' },
    { name: 'Tunisia', formalName: 'Republic of Tunisia' },
    { name: 'Turkey', formalName: 'Republic of Turkey' },
    { name: 'Turkmenistan', formalName: '' },
    { name: 'Tuvalu', formalName: '' },
    { name: 'Uganda', formalName: 'Republic of Uganda' },
    { name: 'Ukraine', formalName: '' },
    { name: 'United Arab Emirates', formalName: '' },
    { name: 'United Kingdom', formalName: 'United Kingdom of Great Britain and Northern Ireland' },
    { name: 'United States', formalName: 'United States of America' },
    { name: 'Uruguay', formalName: 'Oriental Republic of Uruguay' },
    { name: 'Uzbekistan', formalName: 'Republic of Uzbekistan' },
    { name: 'Vanuatu', formalName: 'Republic of Vanuatu' },
    { name: 'Vatican City', formalName: 'Vatican City State' },
    { name: 'Venezuela', formalName: 'Bolivarian Republic of Venezuela' },
    { name: 'Vietnam', formalName: 'Socialist Republic of Vietnam' },
    { name: 'Yemen', formalName: 'Republic of Yemen' },
    { name: 'Zambia', formalName: 'Republic of Zambia' },
    { name: 'Zimbabwe', formalName: 'Republic of Zimbabwe' }
  ])
}

exports.down = function (knex, Promise) {
  return knex('countries').del()
}
