module.exports.TEMPLATE_INDEX_PAGE = 'indexPage'
module.exports.TEMPLATE_TEAMS_PAGE = 'teamsPage'
module.exports.TEMPLATE_NEWS_PAGE = 'newsPage'
module.exports.TEMPLATE_CATEGORIES_PAGE = 'categoriesPage'
module.exports.TEMPLATE_TEAM_PROFILE_PAGE = 'teamProfile'
module.exports.TEMPLATE_SCOREBOARD_PAGE = 'scoreboardPage'
module.exports.TEMPLATE_TASKS_PAGE = 'tasksPage'
module.exports.TEMPLATE_TASK_STATISTICS_PAGE = 'taskStatisticsPage'
module.exports.TEMPLATE_ABOUT_PAGE = 'aboutPage'
module.exports.TEMPLATE_CONTEST_PAGE = 'contestPage'
module.exports.TEMPLATE_REMOTE_CHECKERS_PAGE = 'remoteCheckersPage'
module.exports.TEMPLATE_SUPERVISOR_SIGNIN_PAGE = 'supervisorSigninPage'
module.exports.TEMPLATE_TEAM_SIGNIN_PAGE = 'teamSigninPage'
module.exports.TEMPLATE_TEAM_RESTORE_PAGE = 'teamRestorePage'
module.exports.TEMPLATE_TEAM_SIGNUP_PAGE = 'teamSignupPage'
module.exports.TEMPLATE_TEAM_VERIFY_EMAIL_PAGE = 'teamVerifyEmailPage'
module.exports.TEMPLATE_TEAM_RESET_PASSWORD_PAGE = 'teamResetPasswordPage'
module.exports.TEMPLATE_404_PAGE = '404Page'
module.exports.TEMPLATE_500_PAGE = '500Page'
module.exports.TEMPLATE_ROBOTS_PAGE = 'robots'

module.exports.TEMPLATE_ANALYTICS = 'analytics'

module.exports.TEMPLATE_NAVBAR = 'navbar'
module.exports.TEMPLATE_STREAM_STATE_PARTIAL = 'streamStatePartial'

module.exports.TEMPLATE_STATUSBAR = 'statusbar'
module.exports.TEMPLATE_CONTEST_STATE_PARTIAL = 'contestStatePartial'
module.exports.TEMPLATE_CONTEST_TIMER = 'contestTimer'
module.exports.TEMPLATE_CONTEST_SCORE = 'contestScore'

module.exports.TEMPLATE_TEAM_LIST = 'teamList'
module.exports.TEMPLATE_TEAM_CARD = 'teamCard'

module.exports.TEMPLATE_POST_LIST = 'postList'
module.exports.TEMPLATE_POST_PARTIAL = 'postPartial'
module.exports.TEMPLATE_POST_SIMPLIFIED_PARTIAL = 'postSimplifiedPartial'

module.exports.TEMPLATE_CATEGORY_LIST = 'categoryList'
module.exports.TEMPLATE_CATEGORY_PARTIAL = 'categoryPartial'

module.exports.TEMPLATE_TEAM_PROFILE_PARTIAL = 'teamProfilePartial'

module.exports.TEMPLATE_SCOREBOARD_TABLE = 'scoreboardTable'
module.exports.TEMPLATE_SCOREBOARD_TABLE_ROW_PARTIAL = 'scoreboardTableRowPartial'

module.exports.TEMPLATE_TASK_CONTENT_PARTIAL = 'taskContentPartial'
module.exports.TEMPLATE_CREATE_TASK_HINT_TEXTAREA_PARTIAL = 'createTaskHintTextareaPartial'
module.exports.TEMPLATE_CREATE_TASK_ANSWER_INPUT_PARTIAL = 'createTaskAnswerInputPartial'
module.exports.TEMPLATE_CREATE_TASK_REWARD_SCHEME_PARTIAL = 'createTaskRewardSchemePartial'
module.exports.TEMPLATE_CREATE_TASK_CHECK_METHOD_PARTIAL = 'createTaskCheckMethodPartial'
module.exports.TEMPLATE_EDIT_TASK_HINT_TEXTAREA_PARTIAL = 'editTaskHintTextareaPartial'
module.exports.TEMPLATE_EDIT_TASK_ANSWER_INPUT_PARTIAL = 'editTaskAnswerInputPartial'
module.exports.TEMPLATE_EDIT_TASK_REWARD_SCHEME_PARTIAL = 'editTaskRewardSchemePartial'
module.exports.TEMPLATE_EDIT_TASK_CHECK_METHOD_PARTIAL = 'editTaskCheckMethodPartial'
module.exports.TEMPLATE_TASK_LIST = 'taskList'
module.exports.TEMPLATE_TASK_CARD = 'taskCard'
module.exports.TEMPLATE_REVISE_TASK_STATUS_PARTIAL = 'reviseTaskStatusPartial'
module.exports.TEMPLATE_SUBMIT_TASK_STATUS_PARTIAL = 'submitTaskStatusPartial'

module.exports.TEMPLATE_REMOTE_CHECKER_LIST = 'remoteCheckerList'
module.exports.TEMPLATE_REMOTE_CHECKER_BLOCK = 'remoteCheckerBlock'
