
export default {
  TASK_INITIAL: 1,
  TASK_OPENED: 2,
  TASK_CLOSED: 3,

  CONTEST_INITIAL: 1,
  CONTEST_STARTED: 2,
  CONTEST_PAUSED: 3,
  CONTEST_FINISHED: 4,

  TASK_MIN_VALUE: 10,
  TASK_MAX_VALUE: 1000,
  TASK_MAX_HINTS: 10,
  TASK_MAX_CATEGORIES: 5,
  TASK_MAX_ANSWERS: 15,

  TASK_SUBMIT_LIMIT_TIME: 10,
  TASK_SUBMIT_LIMIT_ATTEMPTS: 3,

  LOG_TEAM_TASK_SUBMIT_ERROR: 1,
  LOG_TEAM_TASK_SUBMIT_SUCCESS: 2,

  POSTGRES_UNIQUE_CONSTRAINT_VIOLATION: '23505'
}
