#!/usr/bin/env bash
USERNAME=volgactf
IMAGE=volgactf-qualifier-backend
docker build --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg BUILD_VERSION=$(cat VERSION) --build-arg VCS_REF=$(git rev-parse --short HEAD) -t $USERNAME/$IMAGE:latest .
